#!/usr/bin/python3

print('Content-type:text/html\r\n\r\n')
print('<html>')
print('<head>')
print('</head>')
print('<body>')
print('<form action="createnote.cgi" method="POST">')
print('<p>Name of poster <input type="text" name="name" required="required" pattern="[a-zA-Z][a-zA-Z.'' ]{0,}" title="1st character must be a letter and no special characters are allowed"/></p>')
print('<p>The message <input type="text" name="message" required="required" pattern="[a-zA-Z0-9][a-zA-Z0-9-.,?!'' += ]{0,}" title="1st character must be a letter/number and only .,-?!''+= characters allowed"></p>')
print('<p><button type="submit">go</button></p>')
print('</form>')
print('<p>or, get a message</p>')
print('<form action="getnote.cgi" method="GET">')
print('<p>Message key: <input type="text" name="key" /></p>')
print('<p><button type="submit">go</button></p>')
print('</form>')
print('</body>')
print('</html>')
